services:
  - type: web
    name: cine-list-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: true
      - key: DB_PORT
        sync: true
      - key: DB_NAME
        sync: true
      - key: DB_USER
        sync: true
      - key: DB_PASSWORD
        sync: true
      - key: JAVA_OPTS
        value: "-Dspring.profiles.active=prod -Dserver.port=10000"
        sync: false
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html