services:
  - type: web
    name: cine-list-app
    runtime: docker
    plan: free
    startCommand: ""
    envVars:
      - key: DB_HOST
        sync: true
      - key: DB_PORT
        sync: true
      - key: DB_NAME
        sync: true
      - key: DB_USER
        sync: true
      - key: DB_PASSWORD
        sync: true
      - key: DB_SSL_MODE
        sync: true
      - key: API_SECURITY_TOKEN_SECRET
        sync: true
