services:
  - type: web
    name: cine-list-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_SECURITY_TOKEN_SECRET
        sync: true
      - key: DB_PASSWORD
        sync: true
      - key: DB_URL
        sync: true
      - key: DB_USERNAME
        sync: true